[package]
name = "contacts-app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.1.9"
regex = "1"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
shlex = "1.1.0"
