[package]
name = "contacts-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.9"
lazy_static = "1.4.0"
regex = "1"
shlex = "1.1.0"
