[package]
name = "contacts-app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.2.1"
dotenvy = "0.15.7"
redis = "0.22.3"
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
shlex = "1.1.0"